name: Send emails daily
on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

jobs:
  calculate-and-send:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup uv
          uses: astral-sh/setup-uv@v3
          with:
            version: '0.5.4'
        
        - name: Run script
          env:
            ZOTERO_ID: ${{ secrets.ZOTERO_ID }}
            ZOTERO_KEY: ${{ secrets.ZOTERO_KEY }}
            ARXIV_QUERY: ${{ secrets.ARXIV_QUERY }}
            SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
            SMTP_PORT: ${{ secrets.SMTP_PORT }}
            SENDER: ${{ secrets.SENDER }}
            RECEIVER: ${{ secrets.RECEIVER }}
            SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
            MAX_PAPER_NUM: ${{ secrets.MAX_PAPER_NUM }}
          run: |
            uv run main.py
